[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
match_indent = true
pattern = '''--cull the pool'''
position = 'before'
payload = '''_starting_pool = hamod_chaos_voucher(_type, _starting_pool)'''
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/game_object.lua"]'''
match_indent = false
pattern = '''
create_UIBox = function(self)
'''
position = 'after'
payload = '''
local hamod_chaos = hamod_create_UIBox and hamod_create_UIBox(self)
if hamod_chaos then return hamod_chaos end
'''
times = 1